# mysql
spring:
  datasource:
    #MySQL配置
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.184.129:3306/gulimall_pms?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848 #配置nacos
      config:
        server-addr: 127.0.0.1:8848 #配置nacos
    alicloud:
      oss:
        endpoint: oss-cn-shanghai.aliyuncs.com
      access-key: LTAI5tMSzKKxKXrtbzFRYwGS
      secret-key: yl4Zaa6TXQLO20Y8v2I9IDCCP6ZZUx
  application:
    name: gulimall-product #服务名称
  thymeleaf:
    cache: false
  redis:
    port: 6379
    host: 192.168.184.129

mybatis-plus:
  mapperLocations: classpath:mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1 #删除
      logic-not-delete-value: 0 #未删除
server:
  port: 10000

logging:
  level:
    com.atgui.gulimall: debug

gulimall:
  thread:
    core-pool-size: 20
    maximum-pool-size: 200
    keep-alive-time: 10



