# mysql
spring:
  datasource:
    #MySQL配置
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.111.132:3306/gulimall_oms?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848 #配置nacos
  application:
    name: gulimall-order #服务名称
  #RabbitMq
  rabbitmq:
    password: guest
    username: guest
    host: 192.168.111.132
    virtual-host: /
    port: 5672
    #开启发送端确定
    publisher-confirms: true
    #开启发送端正确发送到队列
    publisher-returns: true
    #只要抵达队列，异步发送优先回调 publisher-returns
    template:
      mandatory: true
    #开启手动模式
    listener:
      simple:
        acknowledge-mode: manual
  thymeleaf:
    cache: false
  redis:
    host: 192.168.111.132
    port: 6379
  session:
    store-type: redis
  mvc:
    date-format: yyyy-MM-dd HH:mm:ss


mybatis-plus:
  mapperLocations: classpath:mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
server:
  port: 9000

gulimall:
  thread:
    core-pool-size: 20
    maximum-pool-size: 200
    keep-alive-time: 10

alipay:
  app_id: 2021000121669224
  merchant_private_key: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCFHcUA5Ud26I9Al9nTAvGBa40QKqe+018rmz8/wfh7gtSg5lwrQdq9LMNsZotpXZaoBy88Zj47vHejqo34ncoKjGF9h9zNjFf3ZeGE+iMPZ4nRy6S0ZE7topwL5yRHer1Z319ZZ4024ttNcJuA154zBy70rH4kjXKuJocDmayB+4kl1js2WaC26vjL0qSHqX74kAd6lPkxBvtg3qZ7yUKxu3t4WBeJQxhn6tgW5KltlV9hMV3q26S/mpKPM2HlnwftBSEgHnbSt+/hDlCFZpeMcGp1rBzYMra8dhpFmei/1xBpvhoxWL3r4TVXiwCicMZ5CRq5ZbPasmwmGQqMGwqzAgMBAAECggEAJBThpVCAgnae/b8rR8rwc0gXwF4PgeYBUeyOxFVraO8Ze1N1gDQlekl73xIcj77Sa1EnOJPuInr/YtmECfObJCjQ9Bmze/OilGiFLGowvqgt7zPnvQ3DZx5Adel9J/LZCFdHnRA4crwi/Wacf9vyAZrc22018+pzP0kqJ4ur+r8xKP+bLRwdWhdKWs4WgsKxOjjSaWGXH2Qh+2DvKwU7fZkDAXxd4TRElJAeFQSdFEN/QVwsgy/nxFg9tOgKBdfQh+/MbOeEUWJST4ZTM66yJ4qpIgMY5Tjda3+/pPf72zQLwFZI/jfwf3TWrnjJ5HmtehxYkXvKAGz1qwZt9wY54QKBgQDkAVbQ92VtaJE4IO8v0fWek8HyrhzloiCnVZ17tlNAJ9/t7FDxWRYuVrp2m5orWZu5S9A63jZJa4cwg0J6POIpIwPsx9jxwhNyvO2Cam6k/OYJkBRCizx4nbrh41TPRZ8UNHLcaOdRsdnwIFFEfnPo1544RRBLZch++Svhg/UCxwKBgQCVdeGGE/YRNM4D92BpHGh6O/aJ5qPDiIMLXG8Su/GfHkkRsLLwf5QwF+xhLVEIpKevWhmham2DnlJqrUNo7dPHVM7u33L725JHCzdrj8l1nMl9XRZXRQoIyyE0ve4o0pbiJbNUFY7lztkCL1X5vpjS+CV/2w0hCCc68Dmj94tMtQKBgFRGqnBTAYqPPB4jDkX+tWsH8ohhEw1OAAPaAXvYyKzOEFdBIioTY799Dy8IFNQxKv4yp6UavbYlqLKl0cyc9HuAFdNPi0DRG58tdhzeekdBs0WVm+d8z71Fj+4uuQpkEYjGWi5eGCJ6OrQnPeKzWuSVzkW+QWedF57XOwEAZW/BAoGAFPOQaL41mVXgp1evMSzlTHVJay1kuY1SaW5Mt8CW72pMbelqPCJ2QIOqBDlZCbAjPYaQ3zrPHUs9XGzrbTMho+i0lXHHaZzvFXxyCWb/o7gV2rgI4LTx4ievgPg7AYf71LnaOKhI/tgPPaorEDZyr+hPQWwQnBfLgAya1+xkn50CgYEAxfv67hS+ntOMTlWC+tO1iv4DjOaEFPoefJMchdjET2MvnRqWLuihp/zwkaRcpLrRJtMzX1emik1ClFGF+l/tDq7wDBS8FWRykqMJTWobYJJr3Nej8SVf6maODyAb6Epo38suS0xXE1VTrToHJDH568TKtOhg7lbkFY4npwr2oYQ=
  alipay_public_key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA6+svyDg7oJZCz1VO0I6I+7y5ngVjhWvSowYO73YX7+XNaLf7vaB8J3xOg6lJqA20TCF0C7JrmOn3SSB9tuYW3NZbFAY01nC9sli8aBEIdWuny7CyQU047q78v6mvozaETxeqYBdv8csntnQ3waLdZ1+bUD0kjYwD8t1g4fjZR8qGoQfoalu6II1BD9lNKJIcqns3drUQNaJqY0Ns1zT5gbo12WijeFZD98SGLN0IcfTD8KoSUu3fdFh6MGR5NJbnjTyleff6KpCAJE0uK27UtELUb8wUlQ/GDEE+VAX+QTvs7ZUXeJ1Trw3Jgl7yvpsGymCMH+3NzgyVE7wcbKX9HQIDAQAB
  notify_url: http://djx0530.w3.luyouxia.net/payed/notify
  return_url: http://member.gulimall.com/memberOrder.html
  sign_type: RSA2
  charset: utf-8
  gatewayUrl: https://openapi.alipaydev.com/gateway.do


