spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      routes:
        # 库存服务网关
        - id: ware_router
          uri: lb://gulimall-ware
          predicates:
            - Path=/api/ware/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}
          #  http://localhost:88/api/ware/** --> http:localhost:11000/member/**

        # 会员服务网关
        - id: member_router
          uri: lb://gulimall-member
          predicates:
            - Path=/api/member/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}
          #  http://localhost:88/api/member/** --> http:localhost:8000/member/**
        # 优惠服务网关
        - id: coupon_router
          uri: lb://gulimall-coupon
          predicates:
            - Path=/api/coupon/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}
          #  http://localhost:88/api/member/** --> http:localhost:8000/member/**
        # 优惠服务网关
        - id: order_router
          uri: lb://gulimall-order
          predicates:
            - Path=/api/order/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}
          #  http://localhost:88/api/member/** --> http:localhost:8000/member/**

        # 第三方服务网关
        - id: third-party_router
          uri: lb://gulimall-third-party
          predicates:
            - Path=/api/thirdparty/**
          filters:
            - RewritePath=/api/thirdparty/(?<segment>.*),/$\{segment}
          #  http:localhost:88/api/thirdparty --> http:localhost:30000/gulimall-third-party/**

        # 商品网关
        - id: product_router
          uri: lb://gulimall-product
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}
          #  http:localhost:88/api/product --> http:localhost:10000/gulimall-product/**

        #后台网关
        - id: admin_router
          uri: lb://renren-fast
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/(?<segment>.*),/renren-fast/$\{segment}
          #  http:localhost:88/api/** ---> http:localhost:8080/renren-fast/api/**

        #nginx 谷粒网关
        - id:  gulimall_host_route
          uri: lb://gulimall-product
          predicates:
            - Host=gulimall.com,item.gulimall.com
        #nginx search
        - id: gulimall_search_route
          uri: lb://gulimall-search
          predicates:
            - Host=search.gulimall.com
        #nginx search
        - id: gulimall_auth_route
          uri: lb://gulimall-auth-server
          predicates:
            - Host=auth.gulimall.com
        #nginx search
        - id: gulimall_cart_route
          uri: lb://gulimall-cart
          predicates:
            - Host=cart.gulimall.com
        #nginx search
        - id: gulimall_order_route
          uri: lb://gulimall-order
          predicates:
            - Host=order.gulimall.com
        #nginx search
        - id: gulimall_member_route
          uri: lb://gulimall-member
          predicates:
            - Host=member.gulimall.com


#前端项目 /api/**
# 解决方法 断言之后过滤掉api  路径重写
# filters: - RewritePath=/api/(?<segment>.*),/gulimall-product/$\{segment}



