spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    alicloud:
      access-key: LTAI5tMSzKKxKXrtbzFRYwGS
      secret-key: yl4Zaa6TXQLO20Y8v2I9IDCCP6ZZUx
      oss:
        endpoint: oss-cn-shanghai.aliyuncs.com
        bucket: gulimall-djx
      sms:
        host: https://dfsns.market.alicloudapi.com
        path: /data/send_sms
        skin: 1
        sign: 175622
        appcode: 64c7f8ed478c4e85aec9e0f973e7e2ff



  application:
    name: gulimall-third-party
server:
  port: 30000