spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    alicloud:
      access-key: LTAI5tMSzKKxKXrtbzFRYwGS
      secret-key: yl4Zaa6TXQLO20Y8v2I9IDCCP6ZZUx
      oss:
        endpoint: oss-cn-shanghai.aliyuncs.com
        bucket: gulimall-djx


  application:
    name: gulimall-third-party
server:
  port: 30000