spring:
  application:
    name: gulimall-cart
  redis:
    port: 6379
    host: 192.168.111.132
  session:
    store-type: redis
  thymeleaf:
    cache: false
server:
  port: 40000

gulimall:
  thread:
    core-pool-size: 20
    maximum-pool-size: 200
    keep-alive-time: 10